### PR TITLE
Feature/mg/albums

### PR DESCRIPTION
**Pull request by mangei**
- album listing
 - random songs

### CODE REVIEW

**Comment by rieder91** [comment]
how many songs is "Random" supposed to return?
why is "Random" the second tab? aren't artists and albums more important?

**Comment by rieder91** [comment]
I also think that we should show the name of the artist in the album view

=> for example there are tons of albums named "best of"

**Comment by rieder91** [comment]
btw: does it work with duplicate album names of different artists?

for example: 
bruce springsteen - best of
the beatles - best of

**Comment by mangei** [comment]
> how many songs is "Random" supposed to return?

currently it is the same amount, like elements on a single page, by default

> why is "Random" the second tab? aren't artists and albums more important?

First, it was suggested to have it at first glance, but with we show now all songs there, because this function came more or less for free from the library. So I put the random song feature at the second position.

> I also think that we should show the name of the artist in the album view
> => for example there are tons of albums named "best of"

please put this on your "improvements" list

> does it work with duplicate album names of different artists?

Only the album names get aggregated; independend of the artist. So there will only be one "best of" album item.

**Comment by mangei** [comment]
I did a rebase.

**Comment by rieder91** [comment]
> please put this on your "improvements" list
wat list?

> Only the album names get aggregated; independend of the artist. So there will only be one "best of" album item.
it is possible to aggregrate on two keys?

**Comment by mangei** [comment]
> wat list?

As I wrote in Skype. Just a normal list of improvements, we can make to our product which we can present. 

> it is possible to aggregrate on two keys (album and artist)?

yes

**Pull request merged**
